# Generated by Django 3.2.23 on 2024-12-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjVxyq',
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='adUnitId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='appid1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='appid2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='appid3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='appid4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='code_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='code_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='data_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='downurl_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='photo_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='photo_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='pics_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='slave_addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='title_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='djvxymq',
            name='title_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
